### ISSUE TITLE
Verify new Chrome features on other platforms

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam2#14]
- [x] Better Ad Detection (check nytimes.com)
- [x] Badge count updating
    - [x] whenever a new ad is found
    - [x] whenever the user switches tabs
    - [x] whenever clear ads (including the deletion using right click) (see #41)
- [x] Menu/Settings button goes to combined settings page
    - [x] open settings page in new tab instead of new window (see #22)
- [x] Import ads
    - [ ] support for legacy ad import files (see #37)
- [x] Export ads
- [x] Clear ads (does not consider badge count update) (see #55)
- [x] Delete-Adset (via right-click) in Vault (does not consider badge count update) (see #56)

....

**Comment by CyrusSUEN** [comment]
Hasn't the Badge count updating already been done in dca5e3bda0695c95cccdc1c032b8ce5278b76f6d?

**Comment by dhowe** [comment]
As we discussed previously, you are supposed to be checking that these features (already implemented in Chrome) work correctly in Opera and Firefox.

**Comment by CyrusSUEN** [comment]
- [ ] Better Ad Detection (check nytimes.com)
- [x] Badge count updating
   - [x] whenever a new ad is found
   - [x] whenever the user switches tabs
- [x] Localization

**Comment by dhowe** [comment]
They were disabled b/c of possible slowing down of browser. We need to find the right place to insert the updateBadge call.

**Comment by dhowe** [comment]
@CyrusSUEN list updated above...

**Comment by CyrusSUEN** [comment]
> recheck

No problem on all platform on badge-count updating on tab-switches

Menu/Settings button goes to combined settings page - No problem on Chrome and Opera. On Firefox the settings page is opened in a new window instead of a new tab.

Import/Export/Clear buttons in settings - On Chrome and Fireox upon exporting ads it requires a already existed file to be selected to export. (e.g. I need to create a export-ads.json file manually before select that file to use the function)
And the import ads does not work.

**Comment by dhowe** [comment]
Import ads works in Chrome. Do you mean that it does now work in Firefox?

**Comment by CyrusSUEN** [comment]
> Import ads works in Chrome

It actually works on both platforms. I was misusing it as I imported the empty manually created json file. 
After fixing https://github.com/dhowe/AdNauseam2/issues/39 it will be all good.

**Comment by CyrusSUEN** [comment]
Fixed #39; validated Export on checklist.

**Comment by dhowe** [comment]
Please update checklist above

**Comment by CyrusSUEN** [comment]
> update checklist(s) above and note any remaining items below.

Updated above and listing remaining items: 
 - [ ] whenever clear ads (including the deletion using right click) (see #41)
 - [ ] open settings page in new tab instead of new window (see #22)
 - [ ]  support for legacy ad import files (see #37)
 - [ ] Clear ads (does not consider badge count update) (see #55)
 - [ ]  Delete-Adset (via right-click) in Vault (does not consider badge count update) (see #56)

**Comment by CyrusSUEN** [comment]
Just updated the above checklist.

One remained to be fixed on all platforms: https://github.com/dhowe/AdNauseam2/issues/37#issuecomment-210955173

**Comment by dhowe** [comment]
Can this be closed for now?

**Comment by CyrusSUEN** [comment]
> Can this be closed for now?

Yes. After the reversion everything works.
